### ISSUE TITLE
Error about credentials

### ISSUE THREAD

**Issue by victorpiedra** [ibmtjbot/tjbot#112]
Could you help me solve this error, please.

I need a user and password but in IBM Blumix just generate a “apikey”

try deleting the user part and password, replacing it with the apikey but generating the same error

pi@Robotix:~/tjbot/recipes/conversation $ sudo node conversation.js
verbose: TJBot initializing microphone
verbose: TJBot initializing LED
verbose: TJBot initializing servo motor on PIN 7
verbose: TJBot initializing Camera
verbose: TJBot initializing assistant service
verbose: TJBot initializing speech_to_text service
verbose: TJBot initializing text_to_speech service
verbose: TJBot initializing visual_recognition service
/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:542
            throw new Error(
            ^

Error: Missing authentication credentials for tone_analyzer service: username/password or apikey are required.
    at TJBot._createServiceAPI (/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:542:19)
    at new TJBot (/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:116:18)
    at Object.<anonymous> (/home/pi/tjbot/recipes/conversation/conversation.js:40:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by ing-jlgonzalezb** [comment]
I have the same error...

#111

**Comment by hiqdare** [comment]
Missing authentication credentials for tone_analyzer service: username/password or apikey
I submitted a pull request to fix the error. The problem is, in the config_default.json it is saying api_key instead of apikey, which I fixed and submitted in a separate pull request. also changed for STT and TTS from username and password to apikey and url, which is the new information required for newly instantiated services.

**Comment by Ypsilom** [comment]
Actually, I still have the error after updating STT and TTS to apikey and url instead of password and username - is there anything else which needs to be changed?

**Comment by hiqdare** [comment]
you also need to change api_key at visial recognition to apikey

Ypsilom <notifications@github.com> schrieb am So. 11. Nov. 2018 um 23:44:

**Comment by jweisz** [comment]
IAM authentication issues were resolved in https://github.com/ibmtjbot/tjbot/pull/124, which will be merged into master this week.
